name: Android Production Release
on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TERM: term
      KEYSTORE_PATH: ${{ vars.KEY_FILE_PATH }}
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEYSTORE_ENCRYPT_KEY: ${{ secrets.KEYSTORE_ENCRYPT_KEY }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'zulu'

      - name: Decrypt secrets
        run: |
          echo "KEYSTORE_PATH"
          echo ${{ env.KEYSTORE_PATH }}
          gpg --batch --yes --quiet --decrypt --passphrase=${{ env.KEYSTORE_ENCRYPT_KEY }} --output ${{ env.KEYSTORE_PATH }} release/release.gpg
          echo "./release"
          ls ./release
          echo "./app"
          ls ./app
          echo "ls ./"
          ls ./

      - name: Build release artifacts
        run: |
          echo "KEY_FILE_PATH"
          echo ${{ env.KEY_FILE_PATH }}
          echo "app"
          ls ./app
          echo "./app/release"
          ls ./app/release
          echo "./release"
          ls ./release
          rm -rf /android/build 
          rm -rf /android/app/build
          rm -rf /android/.gradle
          ./gradlew --no-daemon app:bundleRelease app:assembleRelease -Pandroid.injected.signing.store.file=${{ vars.KEY_FILE_PATH_JKS }} -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASSWORD }} -Pandroid.injected.signing.key.alias=${{ secrets.KEY_ALIAS }} -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }}

      - name: Check output files
        run: |
          ls app/build/outputs/apk/release/
          ls app/build/outputs/bundle/release/

      - name: Clean secrets
        run: |
          rm -f ${{ vars.KEY_FILE_PATH }}
          ls ./release

      - name: Upload Release Build to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-artifacts
          path: |
            app/build/outputs/apk/release/
            app/build/outputs/bundle/release/

      - name: Create Github Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          prerelease: true
          files: |
            app/build/outputs/apk/release/app-release.apk
            app/build/outputs/bundle/release/app-release.aab