name: iOS UI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  iosTest:
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: swift package resolve

      - name: Run Tests on iPhone 14 Simulator (iOS 16.0)
        run: |
          xcodebuild test \
            -scheme 'Requestify' \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.0' \
            -resultBundlePath TestResults

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports-iPhone14-OS16
          path: TestResults